package com.ohuo.application.services.dto

import kotlinx.serialization.Serializable

@Serializable
data class SettingsSearch(
    val allowIPs: String = "",
    val apiInterfaceStatus: String = "",
    val apiKey: String = "",
    val apiKeyValidityTime: String = "",
    val appStoreLastModified: String = "",
    val appStoreSyncStatus: String = "",
    val appStoreVersion: String = "",
    val autoRestart: String = "",
    val bindAddress: String = "",
    val bindDomain: String = "",
    val complexityVerification: String = "",
    val defaultNetwork: String = "",
    val developerMode: String = "",
    val dingVars: String = "",
    val dockerSockPath: String = "",
    val email: String = "",
    val emailVars: String = "",
    val expirationDays: String = "",
    val expirationTime: String = "",
    val fileRecycleBin: String = "",
    val ipWhiteList: String = "",
    val ipv6: String = "",
    val language: String = "",
    val lastCleanData: String = "",
    val lastCleanSize: String = "",
    val lastCleanTime: String = "",
    val localTime: String = "",
    val menuTabs: String = "",
    val messageType: String = "",
    val mfaInterval: String = "",
    val mfaSecret: String = "",
    val mfaStatus: String = "",
    val monitorInterval: String = "",
    val monitorStatus: String = "",
    val monitorStoreDays: String = "",
    val noAuthSetting: String = "",
    val ntpSite: String = "",
    val panelName: String = "",
    val port: String = "",
    val proxyPasswd: String = "",
    val proxyPasswdKeep: String = "",
    val proxyPort: String = "",
    val proxyType: String = "",
    val proxyUrl: String = "",
    val proxyUser: String = "",
    val securityEntrance: String = "",
    val serverPort: String = "",
    val sessionTimeout: String = "",
    val snapshotIgnore: String = "",
    val ssl: String = "",
    val sslType: String = "",
    val systemIP: String = "",
    val systemVersion: String = "",
    val theme: String = "",
    val timeZone: String = "",
    val userName: String = "",
    val weChatVars: String = "",
    val xpackHideMenu: String = ""
)
